name: libecc

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        blinding: [0, 1]
        complete: [0, 1]
        ladder: [0, 1]
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2      
      # Run actions
      # Vanilla tests
      - name: vanilla tests
        env:
          CC: ${{ matrix.cc }}
          BLINDING: ${{ matrix.blinding }}
          COMPLETE: ${{ matrix.complete }}
          LADDER: ${{ matrix.ladder }}
        shell: bash
        run: |
          # Test expansion scripts
          echo "y" | python2 scripts/expand_libecc.py --remove-all && PYTHON=python2 sh scripts/gen_curves_tests.sh && make clean && make && ./build/ec_self_tests vectors && ./build/ec_self_tests rand;
          echo "y" | python3 scripts/expand_libecc.py --remove-all && PYTHON=python3 sh scripts/gen_curves_tests.sh && make clean && make && ./build/ec_self_tests vectors && ./build/ec_self_tests rand;
          # Nominal vanilla tests
          make && ./build/ec_self_tests vectors && ./build/ec_self_tests rand && cd src/arithmetic_tests/ && make clean && make && make clean && cd -;
          cd src/examples/ && make clean && make && cd - && make clean;
